Add manager info openssl-root command

diff --git a/scripts/manager-info b/scripts/manager-info
--- a/scripts/manager-info
+++ b/scripts/manager-info
@@ -66,6 +66,21 @@ _info_lapack() {
 }
 
 
+_info_openssl_root() {
+    version=1.1.1k
+    if [ ! -z "$1" ]; then
+        version="$1"
+    fi
+    regex="1\.(0\.2[a-u]?|1\.1[a-k]?)"
+    if [ -z $(echo "${version}" | grep -E "^${regex}$" || true) ]; then
+        echo "Invalid openssl version '$1'"
+        exit 1
+    fi
+    version_short=$(echo ${version} | sed -r 's|(([0-9]\.)+[0-9])[a-z]?|\1|g')
+    echo /opt/openssl-${version_short}
+}
+
+
 _info_pyenv_dev() {
     case "$(_info_os_name)" in
         Ubuntu)
@@ -91,16 +106,20 @@ _info_pyenv_dev() {
 
 
 # Parse arguments.
-if [ $# -ne 1 ]; then
-    echo "E: The ${name} command takes one argument"
-    exit 1
-fi
+# if [ $# -ne 1 ]; then
+#     echo "E: The ${name} command takes one argument"
+#     exit 1
+# fi
 case "$1" in
     blas)
         _info_blas
     ;;
     lapack)
         _info_lapack
+    ;;
+    openssl-root)
+        shift
+        _info_openssl_root $@
     ;;
     os-name)
         _info_os_name
